project_id = "clsuecactijyjecxwuxp"

[functions.send-revision-update]
verify_jwt = true

[functions.transactional-email]
verify_jwt = true

[functions.outlook-oauth]
verify_jwt = false

[functions.outlook-calendar]
verify_jwt = true

[functions.outlook-mail]
verify_jwt = true

[functions.outlook-contacts]
verify_jwt = true
