import { readFileSync } from "node:fs";
import assert from "node:assert/strict";
import ts from "typescript";
function load(path) {
  const code = ts.transpileModule(readFileSync(path, "utf8"), { compilerOptions: { module: ts.ModuleKind.CommonJS, target:ts.ScriptTarget.ES2022 } }).outputText;
  const exports = {};
  new Function("exports", code)(exports);
  return exports;
}
const checklist = load("src/lib/planning-checklist.ts");
const legacy = "Existing camera notes\n\nKeep this crew link: https://example.com";
const next = checklist.appendChecklistRow(legacy, "Lens\nkit");
assert.ok(next.startsWith(legacy));
assert.deepEqual(checklist.checklistRows(next), [{ index: 3, checked: false, label: "Lens kit" }]);
const checked = checklist.toggleChecklistRow(next, 3);
assert.equal(checklist.checklistRows(checked)[0].checked, true);
assert.equal(checklist.toggleChecklistRow(checked, 3), next);
assert.equal(checklist.toggleChecklistRow(legacy, 0), legacy);
assert.equal(checklist.appendChecklistRow(legacy, "  "), legacy);
assert.ok(checklist.editChecklistRow(checked,3,"Updated lens").endsWith("- [x] Updated lens"));
assert.equal(checklist.removeChecklistRow(next,3),legacy);
assert.equal(checklist.removeChecklistRow(legacy,0),legacy);
const crew=load("src/lib/crew-plan.ts");
const member={name:"Alex",role:"Producer",reportsTo:"",responsibilities:"Lead interviews"};
const plan=crew.saveCrewRow(legacy,member);
assert.ok(plan.startsWith(legacy));
assert.deepEqual(crew.crewRows(plan),[{index:3,...member}]);
assert.equal(crew.removeCrewRow(plan,3),legacy);
assert.equal(crew.removeCrewRow(legacy,0),legacy);
assert.equal(crew.crewRows('Crew: '+JSON.stringify({...member,index:99}))[0].index,0);
const documents = load("src/lib/document-draft.ts");
const draft = { kind: "Quote", recipient: '<script>alert(1)</script>', reference: '"test"', project: "A & B", date: "2026-09-14", currency: "USD", amount: "123.45", content: "Approved <terms>\nSecond line" };
const html = documents.documentDraftHtml(draft);
assert.deepEqual(documents.readDocumentDraft(draft), draft);
assert.throws(() => documents.readDocumentDraft({ ...draft, currency: "INVALID" }));
assert.throws(() => documents.readDocumentDraft({ ...draft, content: "x".repeat(40001) }));
assert.throws(() => documents.readDocumentDraft(null));
assert.ok(!html.includes("<script>"));
assert.ok(html.includes("&lt;script&gt;"));
assert.ok(html.includes("$123.45"));
assert.ok(html.includes("A &amp; B"));
assert.ok(html.includes("Draft for review"));
assert.ok(!documents.documentDraftHtml({ ...draft, amount: "" }).includes("$0.00"));
assert.equal(documents.moneyCents("0.29"),29);
assert.equal(documents.moneyCents("1.005"),null);
assert.equal(documents.moneyCents("1e3"),null);
assert.equal(documents.moneyCents("-1"),null);
const services={...draft,items:[{description:"Service <one>",quantity:"2.5",rate:"100.10"},{description:"Service two",quantity:"1",rate:"0.29"}]};
assert.equal(documents.draftTotalCents(services),25054);
assert.equal(documents.lineItemCents({quantity:"1.005",rate:"1.00"}),101);
assert.equal(documents.lineItemCents({quantity:"0",rate:"1.00"}),null);
assert.deepEqual(documents.readDocumentDraft(services),services);
assert.throws(()=>documents.readDocumentDraft({...draft,items:[{description:5,quantity:"1",rate:"1"}]}));
assert.ok(documents.documentDraftHtml(services).includes("Service &lt;one&gt;"));
assert.equal(documents.draftFilename({...draft,recipient:"Vendor / Studio",reference:"Q-02"}),"quote-vendor-studio-q-02");
const invoices=load("src/lib/invoice-export.ts");
const invoice={id:"1",number:"INV",description:"Services",amount_cents:10000,amount_paid_cents:2500,currency:"USD",status:"deposit",issued_at:"2026-09-14",due_at:null,paid_at:null};
assert.deepEqual(invoices.invoiceTotals([invoice,{...invoice,id:"2",amount_cents:null,amount_paid_cents:500},{...invoice,id:"3",currency:"EUR",amount_paid_cents:12000}]),[{currency:"USD",billed:10000,paid:3000,balance:7500,unknown:1},{currency:"EUR",billed:10000,paid:12000,balance:-2000,unknown:0}]);
assert.ok(invoices.invoiceReportHtml([invoice]).includes("$75.00"));
assert.ok(invoices.invoiceCsv([invoice]).includes('"10000","2500","7500"'));
const contracts = load("src/lib/contract-export.ts");
const report = contracts.contractReportHtml([{ id: "1", title: "<img onerror=bad>", description: "A & B", status: "signed", sent_at: null, signed_at: "2026-09-14", expires_at: null, hosted_url: "https://secret.example/token" }]);
assert.ok(report.includes("&lt;img onerror=bad&gt;"));
assert.ok(!report.includes("https://secret.example"));
assert.ok(report.includes("2026-09-14"));
const paymentsRoute = readFileSync("src/routes/_authenticated/payments.tsx", "utf8");
const appShell = readFileSync("src/components/app/app-shell.tsx", "utf8");
assert.ok(!paymentsRoute.includes("<AppShell"), "Payments must use the authenticated parent shell");
assert.ok(
  appShell.includes('const useWideCanvas = pathname === "/payments"'),
  "Payments must use the wide authenticated canvas",
);
console.log("Local workflow preservation, amounts and export escaping passed");
